package mockupstream

import (
	"context"
	"encoding/json"
	"fmt"
	"math/rand"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"
)

const (
	defaultAddr                   = ":18080"
	defaultAPIKey                 = "perf-upstream-key"
	defaultRetryableStatus        = 429
	defaultResponseText           = "This is a controlled performance test response generated by the local mock upstream."
	defaultChatPromptTokens       = 128
	defaultChatCompletionTokens   = 256
	defaultResponsesInputTokens   = 256
	defaultResponsesOutputTokens  = 512
	defaultStreamChunks           = 20
	defaultNonStreamDelayMs       = 200
	defaultStreamFirstByteDelayMs = 300
	defaultStreamChunkDelayMs     = 750
)

var defaultModels = []string{
	"bench-chat-upstream",
	"bench-responses-upstream",
}

type Config struct {
	Addr                  string
	APIKey                string
	Models                []string
	NonStreamDelay        time.Duration
	StreamFirstByteDelay  time.Duration
	StreamChunkDelay      time.Duration
	StreamChunks          int
	ChatPromptTokens      int
	ChatCompletionTokens  int
	ResponsesInputTokens  int
	ResponsesOutputTokens int
	ErrorRate             float64
	RetryableRate         float64
	RetryableStatus       int
	ResponseText          string
}

type Server struct {
	cfg Config
}

func DefaultConfig() Config {
	return Config{
		Addr:                  defaultAddr,
		APIKey:                defaultAPIKey,
		Models:                append([]string(nil), defaultModels...),
		NonStreamDelay:        defaultNonStreamDelayMs * time.Millisecond,
		StreamFirstByteDelay:  defaultStreamFirstByteDelayMs * time.Millisecond,
		StreamChunkDelay:      defaultStreamChunkDelayMs * time.Millisecond,
		StreamChunks:          defaultStreamChunks,
		ChatPromptTokens:      defaultChatPromptTokens,
		ChatCompletionTokens:  defaultChatCompletionTokens,
		ResponsesInputTokens:  defaultResponsesInputTokens,
		ResponsesOutputTokens: defaultResponsesOutputTokens,
		RetryableStatus:       defaultRetryableStatus,
		ResponseText:          defaultResponseText,
	}
}

func ConfigFromEnv() Config {
	cfg := DefaultConfig()
	cfg.Addr = getEnv("PERF_MOCK_ADDR", cfg.Addr)
	cfg.APIKey = getEnv("PERF_UPSTREAM_API_KEY", cfg.APIKey)
	cfg.Models = splitCSV(getEnv("PERF_MOCK_MODELS", strings.Join(cfg.Models, ",")), cfg.Models)
	cfg.NonStreamDelay = time.Duration(getEnvInt("PERF_MOCK_NONSTREAM_DELAY_MS", int(cfg.NonStreamDelay/time.Millisecond))) * time.Millisecond
	cfg.StreamFirstByteDelay = time.Duration(getEnvInt("PERF_MOCK_STREAM_FIRST_BYTE_DELAY_MS", int(cfg.StreamFirstByteDelay/time.Millisecond))) * time.Millisecond
	cfg.StreamChunkDelay = time.Duration(getEnvInt("PERF_MOCK_STREAM_CHUNK_DELAY_MS", int(cfg.StreamChunkDelay/time.Millisecond))) * time.Millisecond
	cfg.StreamChunks = getEnvInt("PERF_MOCK_STREAM_CHUNKS", cfg.StreamChunks)
	cfg.ChatPromptTokens = getEnvInt("PERF_MOCK_CHAT_PROMPT_TOKENS", cfg.ChatPromptTokens)
	cfg.ChatCompletionTokens = getEnvInt("PERF_MOCK_CHAT_COMPLETION_TOKENS", cfg.ChatCompletionTokens)
	cfg.ResponsesInputTokens = getEnvInt("PERF_MOCK_RESPONSES_INPUT_TOKENS", cfg.ResponsesInputTokens)
	cfg.ResponsesOutputTokens = getEnvInt("PERF_MOCK_RESPONSES_OUTPUT_TOKENS", cfg.ResponsesOutputTokens)
	cfg.ErrorRate = getEnvFloat("PERF_MOCK_ERROR_RATE", cfg.ErrorRate)
	cfg.RetryableRate = getEnvFloat("PERF_MOCK_RETRYABLE_RATE", cfg.RetryableRate)
	cfg.RetryableStatus = getEnvInt("PERF_MOCK_RETRYABLE_STATUS", cfg.RetryableStatus)
	cfg.ResponseText = getEnv("PERF_MOCK_RESPONSE_TEXT", cfg.ResponseText)
	return sanitizeConfig(cfg)
}

func New(cfg Config) *Server {
	return &Server{cfg: sanitizeConfig(cfg)}
}

func (s *Server) Handler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("/healthz", s.handleHealthz)
	mux.HandleFunc("/v1/models", s.handleModels)
	mux.HandleFunc("/v1/chat/completions", s.handleChatCompletions)
	mux.HandleFunc("/v1/responses", s.handleResponses)
	return mux
}

func (s *Server) ListenAndServe(ctx context.Context) error {
	server := &http.Server{
		Addr:              s.cfg.Addr,
		Handler:           s.Handler(),
		ReadHeaderTimeout: 10 * time.Second,
	}

	go func() {
		<-ctx.Done()
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		_ = server.Shutdown(shutdownCtx)
	}()

	err := server.ListenAndServe()
	if err == nil || err == http.ErrServerClosed {
		return nil
	}
	return err
}

func (s *Server) handleHealthz(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, map[string]any{
		"ok": true,
	})
}

func (s *Server) handleModels(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		writeJSON(w, http.StatusMethodNotAllowed, errorResponse("method_not_allowed"))
		return
	}
	if !s.authorize(w, r) {
		return
	}
	if s.maybeFail(w) {
		return
	}
	if !sleepContext(r.Context(), s.cfg.NonStreamDelay) {
		return
	}

	data := make([]map[string]any, 0, len(s.cfg.Models))
	for _, modelName := range s.cfg.Models {
		data = append(data, map[string]any{
			"id":       modelName,
			"object":   "model",
			"owned_by": "perf-mock",
		})
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"object": "list",
		"data":   data,
	})
}

func (s *Server) handleChatCompletions(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		writeJSON(w, http.StatusMethodNotAllowed, errorResponse("method_not_allowed"))
		return
	}
	if !s.authorize(w, r) {
		return
	}
	if s.maybeFail(w) {
		return
	}

	var req struct {
		Model  string `json:"model"`
		Stream bool   `json:"stream"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, errorResponse("invalid_json"))
		return
	}
	if req.Model == "" {
		req.Model = s.firstModel()
	}

	if req.Stream {
		s.writeChatStream(w, r, req.Model)
		return
	}

	if !sleepContext(r.Context(), s.cfg.NonStreamDelay) {
		return
	}

	response := map[string]any{
		"id":      newID("chatcmpl"),
		"object":  "chat.completion",
		"created": time.Now().Unix(),
		"model":   req.Model,
		"choices": []map[string]any{
			{
				"index": 0,
				"message": map[string]any{
					"role":    "assistant",
					"content": s.cfg.ResponseText,
				},
				"finish_reason": "stop",
			},
		},
		"usage": map[string]any{
			"prompt_tokens":     s.cfg.ChatPromptTokens,
			"completion_tokens": s.cfg.ChatCompletionTokens,
			"total_tokens":      s.cfg.ChatPromptTokens + s.cfg.ChatCompletionTokens,
			"prompt_tokens_details": map[string]any{
				"cached_tokens": 0,
			},
		},
	}
	writeJSON(w, http.StatusOK, response)
}

func (s *Server) handleResponses(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		writeJSON(w, http.StatusMethodNotAllowed, errorResponse("method_not_allowed"))
		return
	}
	if !s.authorize(w, r) {
		return
	}
	if s.maybeFail(w) {
		return
	}

	var req struct {
		Model  string `json:"model"`
		Stream bool   `json:"stream"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, errorResponse("invalid_json"))
		return
	}
	if req.Model == "" {
		req.Model = s.firstModel()
	}

	if req.Stream {
		s.writeResponsesStream(w, r, req.Model)
		return
	}

	if !sleepContext(r.Context(), s.cfg.NonStreamDelay) {
		return
	}
	writeJSON(w, http.StatusOK, s.buildResponsesObject(req.Model))
}

func (s *Server) writeChatStream(w http.ResponseWriter, r *http.Request, modelName string) {
	flusher, ok := w.(http.Flusher)
	if !ok {
		writeJSON(w, http.StatusInternalServerError, errorResponse("streaming_not_supported"))
		return
	}

	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")

	if !sleepContext(r.Context(), s.cfg.StreamFirstByteDelay) {
		return
	}

	chunks := splitText(s.cfg.ResponseText, s.cfg.StreamChunks)
	for index, chunk := range chunks {
		payload := map[string]any{
			"id":      newID("chatcmpl"),
			"object":  "chat.completion.chunk",
			"created": time.Now().Unix(),
			"model":   modelName,
			"choices": []map[string]any{
				{
					"index": 0,
					"delta": map[string]any{
						"content": chunk,
					},
					"finish_reason": nil,
				},
			},
		}
		if index == 0 {
			payload["choices"].([]map[string]any)[0]["delta"] = map[string]any{
				"role":    "assistant",
				"content": chunk,
			}
		}
		if err := writeSSEEvent(w, flusher, "", payload); err != nil {
			return
		}
		if !sleepContext(r.Context(), s.cfg.StreamChunkDelay) {
			return
		}
	}

	usageChunk := map[string]any{
		"id":      newID("chatcmpl"),
		"object":  "chat.completion.chunk",
		"created": time.Now().Unix(),
		"model":   modelName,
		"choices": []any{},
		"usage": map[string]any{
			"prompt_tokens":     s.cfg.ChatPromptTokens,
			"completion_tokens": s.cfg.ChatCompletionTokens,
			"total_tokens":      s.cfg.ChatPromptTokens + s.cfg.ChatCompletionTokens,
			"prompt_tokens_details": map[string]any{
				"cached_tokens": 0,
			},
		},
	}
	if err := writeSSEEvent(w, flusher, "", usageChunk); err != nil {
		return
	}
	_, _ = w.Write([]byte("data: [DONE]\n\n"))
	flusher.Flush()
}

func (s *Server) writeResponsesStream(w http.ResponseWriter, r *http.Request, modelName string) {
	flusher, ok := w.(http.Flusher)
	if !ok {
		writeJSON(w, http.StatusInternalServerError, errorResponse("streaming_not_supported"))
		return
	}

	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")

	if !sleepContext(r.Context(), s.cfg.StreamFirstByteDelay) {
		return
	}

	created := map[string]any{
		"type": "response.created",
		"response": map[string]any{
			"id":     newID("resp"),
			"object": "response",
			"model":  modelName,
		},
	}
	if err := writeSSEEvent(w, flusher, "response.created", created); err != nil {
		return
	}

	chunks := splitText(s.cfg.ResponseText, s.cfg.StreamChunks)
	for _, chunk := range chunks {
		event := map[string]any{
			"type":  "response.output_text.delta",
			"delta": chunk,
		}
		if err := writeSSEEvent(w, flusher, "response.output_text.delta", event); err != nil {
			return
		}
		if !sleepContext(r.Context(), s.cfg.StreamChunkDelay) {
			return
		}
	}

	completed := map[string]any{
		"type":     "response.completed",
		"response": s.buildResponsesObject(modelName),
	}
	if err := writeSSEEvent(w, flusher, "response.completed", completed); err != nil {
		return
	}
	_, _ = w.Write([]byte("data: [DONE]\n\n"))
	flusher.Flush()
}

func (s *Server) buildResponsesObject(modelName string) map[string]any {
	return map[string]any{
		"id":     newID("resp"),
		"object": "response",
		"model":  modelName,
		"output": []map[string]any{
			{
				"id":   newID("msg"),
				"type": "message",
				"role": "assistant",
				"content": []map[string]any{
					{
						"type": "text",
						"text": s.cfg.ResponseText,
					},
				},
			},
		},
		"usage": map[string]any{
			"input_tokens":  s.cfg.ResponsesInputTokens,
			"output_tokens": s.cfg.ResponsesOutputTokens,
			"total_tokens":  s.cfg.ResponsesInputTokens + s.cfg.ResponsesOutputTokens,
			"input_tokens_details": map[string]any{
				"cached_tokens": 0,
			},
		},
	}
}

func (s *Server) authorize(w http.ResponseWriter, r *http.Request) bool {
	if s.cfg.APIKey == "" {
		return true
	}

	authHeader := strings.TrimSpace(r.Header.Get("Authorization"))
	xAPIKey := strings.TrimSpace(r.Header.Get("X-Api-Key"))
	if authHeader == "Bearer "+s.cfg.APIKey || xAPIKey == s.cfg.APIKey {
		return true
	}

	writeJSON(w, http.StatusUnauthorized, errorResponse("unauthorized"))
	return false
}

func (s *Server) maybeFail(w http.ResponseWriter) bool {
	if s.cfg.RetryableRate > 0 && rand.Float64() < s.cfg.RetryableRate {
		writeJSON(w, s.cfg.RetryableStatus, errorResponse("retryable_mock_failure"))
		return true
	}
	if s.cfg.ErrorRate > 0 && rand.Float64() < s.cfg.ErrorRate {
		writeJSON(w, http.StatusInternalServerError, errorResponse("mock_failure"))
		return true
	}
	return false
}

func (s *Server) firstModel() string {
	if len(s.cfg.Models) == 0 {
		return defaultModels[0]
	}
	return s.cfg.Models[0]
}

func sanitizeConfig(cfg Config) Config {
	if cfg.Addr == "" {
		cfg.Addr = defaultAddr
	}
	if cfg.APIKey == "" {
		cfg.APIKey = defaultAPIKey
	}
	if len(cfg.Models) == 0 {
		cfg.Models = append([]string(nil), defaultModels...)
	}
	if cfg.StreamChunks < 1 {
		cfg.StreamChunks = 1
	}
	if cfg.ChatPromptTokens < 1 {
		cfg.ChatPromptTokens = defaultChatPromptTokens
	}
	if cfg.ChatCompletionTokens < 1 {
		cfg.ChatCompletionTokens = defaultChatCompletionTokens
	}
	if cfg.ResponsesInputTokens < 1 {
		cfg.ResponsesInputTokens = defaultResponsesInputTokens
	}
	if cfg.ResponsesOutputTokens < 1 {
		cfg.ResponsesOutputTokens = defaultResponsesOutputTokens
	}
	if cfg.RetryableStatus == 0 {
		cfg.RetryableStatus = defaultRetryableStatus
	}
	if cfg.ResponseText == "" {
		cfg.ResponseText = defaultResponseText
	}
	return cfg
}

func writeJSON(w http.ResponseWriter, statusCode int, payload any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(statusCode)
	_ = json.NewEncoder(w).Encode(payload)
}

func writeSSEEvent(w http.ResponseWriter, flusher http.Flusher, eventName string, payload any) error {
	if eventName != "" {
		if _, err := fmt.Fprintf(w, "event: %s\n", eventName); err != nil {
			return err
		}
	}
	body, err := json.Marshal(payload)
	if err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "data: %s\n\n", body); err != nil {
		return err
	}
	flusher.Flush()
	return nil
}

func errorResponse(message string) map[string]any {
	return map[string]any{
		"error": map[string]any{
			"message": message,
		},
	}
}

func splitText(text string, chunks int) []string {
	if chunks <= 1 || len(text) <= 1 {
		return []string{text}
	}

	runes := []rune(text)
	if len(runes) <= chunks {
		out := make([]string, 0, len(runes))
		for _, value := range runes {
			out = append(out, string(value))
		}
		return out
	}

	out := make([]string, 0, chunks)
	chunkSize := len(runes) / chunks
	remainder := len(runes) % chunks
	start := 0
	for index := 0; index < chunks; index++ {
		size := chunkSize
		if index < remainder {
			size++
		}
		end := start + size
		out = append(out, string(runes[start:end]))
		start = end
	}
	return out
}

func sleepContext(ctx context.Context, delay time.Duration) bool {
	if delay <= 0 {
		return true
	}
	timer := time.NewTimer(delay)
	defer timer.Stop()

	select {
	case <-ctx.Done():
		return false
	case <-timer.C:
		return true
	}
}

func newID(prefix string) string {
	return fmt.Sprintf("%s-%d", prefix, time.Now().UnixNano())
}

func splitCSV(raw string, fallback []string) []string {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return append([]string(nil), fallback...)
	}

	parts := strings.Split(trimmed, ",")
	values := make([]string, 0, len(parts))
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part != "" {
			values = append(values, part)
		}
	}
	if len(values) == 0 {
		return append([]string(nil), fallback...)
	}
	return values
}

func getEnv(key, fallback string) string {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	return value
}

func getEnvInt(key string, fallback int) int {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	parsed, err := strconv.Atoi(value)
	if err != nil {
		return fallback
	}
	return parsed
}

func getEnvFloat(key string, fallback float64) float64 {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	parsed, err := strconv.ParseFloat(value, 64)
	if err != nil {
		return fallback
	}
	return parsed
}
